{% set name = "MetaSBT" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b4995227ee52d73c6bd77c897e1df7ea9d208df6606e1ad211833d4b7cceab3

build:
  number: 0
  noarch: python
  entry_points:
    - metasbt=metasbt.metasbt:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - numpy >=1.19.2
    - pip
    - python >=3.8,<3.9
    - requests >=2.28.0
    - setuptools
  run:
    - biopython >=1.83
    - checkm2 >=1.0.1
    - checkv >=1.0.1
    - eukcc >=2.1.0
    - fastcluster >=1.2.6
    - howdesbt >=2.00.13
    - kitsune >=1.3.3
    - mash >=2.3
    - minimizers >=0.1.2
    - ncbitax2lin >=2.3.2
    - ntcard >=1.2.2
    - numpy >=1.19.2
    - packaging>=23.2
    - python >=3.8
    - requests >=2.28.0
    - tabulate >=0.9.0
    - tqdm >=4.38.0
    - wget >=1.21.3

test:
  imports:
    - metasbt
  commands:
    - pip check
    - metasbt --test all
  requires:
    - pip

about:
  home: https://github.com/cumbof/MetaSBT
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microbial genomes characterization with Sequence Bloom Trees
  description: |
   A scalable framework for automatically indexing microbial genomes and accurately 
   characterizing metagenome-assembled genomes with Sequence Bloom Trees

extra:
  recipe-maintainers:
    - cumbof
