[build-system]
requires = ["setuptools>=68", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "MetaSBT"
dynamic = ["version"]
description = "A scalable framework for automatically indexing microbial genomes and accurately characterizing metagenome-assembled genomes with Sequence Bloom Trees"
readme = "README.md"
license = "MIT"
license-files = [
    "LICENSE",
]
authors = [
    {name = "Fabio Cumbo", email = "fabio.cumbo@gmail.com"},
]
keywords = [
    "bioinformatics",
    "characterization",
    "classification",
    "genomes",
    "metagenome-assembled genomes",
    "metagenomics",
    "microbiome",
    "profiling",
    "sequence bloom trees",
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
requires-python = ">=3.9"
dependencies = [
    "biopython>=1.85",
    "numpy==1.26.4",
    "packaging>=25.0",
    "requests>=2.32.4",
    "scipy>=1.13.1",
    "tabulate>=0.9.0",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
dev = [
    "build>=1.0.0",
    "twine>=4.0.0",
]

[project.scripts]
metasbt = "metasbt.metasbt:run"

[project.urls]
Homepage = "http://github.com/cumbof/MetaSBT"
Source = "https://github.com/cumbof/MetaSBT"
Issues = "https://github.com/cumbof/MetaSBT/issues"
Discussions = "https://github.com/cumbof/MetaSBT/discussions"
Wiki = "https://github.com/cumbof/MetaSBT/wiki"
Databases = "https://github.com/cumbof/MetaSBT-DBs"
Download = "https://pypi.org/project/MetaSBT/"

[tool.setuptools]
include-package-data = true
script-files = ["scripts/get_ncbi_genomes.py"]
packages = {find = {}}

[tool.setuptools.dynamic]
version = {attr = "metasbt.__version__"}

[[tool.setuptools-rust.ext-modules]]
target = "deltatree"
path = "deltatree/Cargo.toml"
binding = "PyO3"
